### ISSUE TITLE
No Floo* commands

### ISSUE THREAD

**Issue by rubik** [Floobits/floobits-neovim#32]
I installed `nvim-python` and confirmed it is working. Then I installed `floobits-neovim` and added the `.floorc.json` file, as per the documentation. When I start `nvim`, however, I cannot use the `:Floo*` commands. Neovim fails with the message "No editor command Floo...".

**Comment by joshuarubin** [comment]
Same here

**Comment by Shougo** [comment]
You should execute `:UpdateRemotePlugins` command.

**Comment by rubik** [comment]
When executing `:UpdateRemotePlugins` I get the error
```
Could not find any plugins when attempting to register plugin commands. See :he
 remote-plugin
```

**Comment by Shougo** [comment]
It is not error message.
It just not found Python3 remote plugins.

**Comment by rubik** [comment]
I'm sorry, I installed neovim through Pip for both Python 2 and 3 and configured the variables

    let g:python_host_prog = '/usr/bin/python2'
    let g:python3_host_prog = '/usr/bin/python'

What else should I do?

**Comment by Shougo** [comment]
After you executed `:UpdateRemotePlugins`, `:Floo*` commands are not found?

**Comment by rubik** [comment]
The command `:UpdateRemotePlugins` gives the same message... What am I missing?

**Comment by joshuarubin** [comment]
On OSX, with homebrew installed python and python3, I had to add

```vim
  let g:python_host_prog  = "/usr/local/bin/python"
  let g:python3_host_prog = "/usr/local/bin/python3"
```

to the top of my `.nvimrc`.

The `Floo` commands then became available.

**Comment by rubik** [comment]
I tried to execute the `Floo*` commands. Now they are available, even though the `:UpdateRemotePlugins` does nothing... I think I can close the issue.

**Comment by Shougo** [comment]
> I'll close the issue, however I don't understand how :UpdateRemotePlugins should work.

It defines `Floo*` commands and make cache it.
But it has confusing warning message.
I think it should be improved.

**Comment by rubik** [comment]
Yes, the current message make it seem that nothing happened.

**Comment by Shougo** [comment]
The message is improved in latest neovim.
Please check it.

**Comment by rubik** [comment]
Yes, now it is indeed clearer. Thank you for you help @Shougo!
