### ISSUE TITLE
:FlooOpenInBrowser causes error "Channel doesn't exist"

### ISSUE THREAD

**Issue by haakenlid** [Floobits/floobits-neovim#35]
This happens when I use `:FlooShareDirPublic .` and then `:FlooOpenInBrowser` 

The documents are not synced, and every single action gives this warning

```
Error detected while processing CursorMovedI Auto commands for "*":                 
E475: Invalid argument: Channel doesn't exist     
```

**Comment by ggreer** [comment]
Python's browser.open() is triggering a weird bug in neovim. Relevant log: https://gist.github.com/ggreer/6cac03efa49a063e1eb8ff19dfe513d6

Relevant bit of neovim code: https://github.com/neovim/neovim/blob/master/src/nvim/msgpack_rpc/helpers.c#L558

`NO_RESPONSE` is -1, which gets cast to an unsigned 64 bit, so it sends a response id of 18 quadrillion. Either neovim's python package should handle this, or neovim shouldn't send ridiculous response ids.

**Comment by ggreer** [comment]
Neovim is getting bad msgpack data because `webbrowser.open()` prints "Created new window in existing browser session." to stdout. Neovim dutifully tries to parse that as msgpack.

**Comment by ggreer** [comment]
Try the latest release (v3.3.3). It should work now.
