### ISSUE TITLE
:FlooOpenInBrowser triggers a bug in neovim

### ISSUE THREAD

**Issue by ggreer** [Floobits/floobits-neovim#41]
Relevant log: https://gist.github.com/ggreer/6cac03efa49a063e1eb8ff19dfe513d6

It looks like the bug is in https://github.com/neovim/neovim/blob/master/src/nvim/msgpack_rpc/helpers.c#L558

NO_RESPONSE is max 64 bit int. :/

**Comment by ggreer** [comment]
Duplicate of #35. Whoops.

**Comment by justinmk** [comment]
What's the bug? Is that value being used as a channel id for some reason?

**Comment by ggreer** [comment]
Explained in https://github.com/Floobits/floobits-neovim/issues/35#issuecomment-278488028 and fixed in https://github.com/Floobits/floobits-neovim/commit/00753bee4e4465914829782e57a1182c765fea15
